packages = ["numpy"]

[splashscreen]
autoclose = true

[[fetch]]
from = "src"
files = ["usa/usa.py", "usa/gol.py"]

[[interpreters]]
src = "https://cdn.jsdelivr.net/pyodide/v0.22.1/full/pyodide.js"
# src = "lib/pyodide-0.22.1/pyodide.js"
name = "pyodide-0.22.1"
lang = "python"
